### PR TITLE
Add nested git generation

### PR DESCRIPTION
**Pull request by JR-1991**
This PR introduces the functionality to add remote models within a given one. This is done by applying the following schema to an attributes `Type`:

```
https://www.github.com/user/mymodel.git@ObjectOfInterest
```

It will add the corresponding object of interest to the generation process of the initial one. We might think about making this more specific by allowing specification of branches/tags/commits to make sure it's actually the intended version of the nested model. Something along that line:

```
ObjectOfInterest@https://www.github.com/user/mymodel.git#somecommit
```

@haeussma what are your thoughts?

**Additional docs**

* This PR also fixes `date` interfering with attributes named the same way by simply import `date` as `Date`.

### CODE REVIEW

**Comment by haeussma** [comment]
I think specifying the object first makes it clearer! Being able to speciefy a commit (if wanted) is also important to have. Good changes!

**Comment by haeussma** [comment]
Being able to choose the commit should also be possible when using ```generate_linking_template()```

**Comment by JR-1991** [comment]
Had a couple thoughts about this and I think it makes sense to restrict this to releases instead of commits. The latter may be too fine-grained and if you want to include a data model within your own, this should be curated and tested version - Which is more likely than using a commit.

What do you think? @haeussma

**Comment by JR-1991** [comment]
As discussed, repo links can now be modified to include tags/branches and commits:

* Using **@** followed by a commit hash will pull from the specified commit
* Using **#** followed by a tag/branch name will pull from the specified release/branch

**Pull request merged**
